#!/usr/bin/bash

clear && cd "$(dirname "$(realpath "$0")")" || echo

if [ ! -d ".cache" ]; then
    mkdir ".cache"
fi

__OS_STATUS=0
export __OS_STATUS
__LINUX=0
export __LINUX
__WINDOWS=0
export __WINDOWS
__DARWIN=0
export __DARWIN
__SAMP_EXEC="null"
export __SAMP_EXEC
__PAWNCC="null"
export __PAWNCC
__DIS_GNU_NANO=""
export __DIS_GNU_NANO
__SAMP_LOG=""
export __SAMP_LOG
__SAMP_NEXT_QUERY=0
export __SAMP_NEXT_QUERY
__SAMP_SERVER=0
export __SAMP_SERVER

MODULE_LOADED_NOTICE=0
DO_NOT_SHOW_LNOT=0

SERVERS_NEXT=0
export SERVERS_NEXT

__cache_save=".cache/compiler.log"
export __cache_save

shell_TITLE=""
export shell_TITLE
shell_DIR="$(dirname "$(realpath "$0")")"
export shell_DIR
shell_NAME="$(basename "$0")"
export shell_NAME
LICENSES="GPL v2.0 or MIT Licenses"
export LICENSES

compiler_MODE="null"
export compiler_MODE
COMPILER_PAWNCC=""
export COMPILER_PAWNCC
COMPILER_NEXT=0
export COMPILER_NEXT

__SAVE_RESET=0
export __SAVE_RESET

SHUSERS="$USER@$(hostname 2> /dev/null || echo )"

function bash_title() {
    echo -ne "\033]0;$1\007"
}
bash_title "$SHUSERS:~"

function bash_coltext_y() {
COLOR_Y="\e[33m"
    local color="$COLOR_Y"
    local text="$1"
    echo -e "${color}${text}\e[0m"
}
export bash_coltext_y

function bash_coltext_g() {
COLOR_G="\e[32m"
    local color="$COLOR_G"
    local text="$1"
    echo -e "${color}${text}\e[0m"
}
export bash_coltext_g

function bash_coltext_r() {
COLOR_R="\e[91m"
    local color="$COLOR_R"
    local text="$1"
    echo -e "${color}${text}\e[0m" 
}
export bash_coltext_r

function bash_coltext_a() {
COLOR_A="\e[97m"
    local color="$COLOR_A"
    local text="$1"
    echo -e "${color}${text}\e[0m"
}
export bash_coltext_a

if [ ! -d ".lib" ]; then
    mkdir ".lib"
fi

function save_TITLE()
{
    title=$1
    shell_TITLE="$title"
    bash_title "$SHUSERS:~/ $shell_TITLE"
}
export save_TITLE

: ' compiler option '
valid_AMX_OPTION=(
    "-A" "-a" "-C+" "-C-" "-c" "-D" "-d0" "-d1" "-d2" "-d3" "-e" "-H" 
    "-i" "-l" "-O" "-p" "-R+" "-R-" "-r" "-S" "-s" "-t" "-v0" "-v1" "-v2"
    "-W" "-X" "-XD" "-Z+" "-Z-" "-E+" "-E-" "-^" "-;+" "-;-" "-(+" "-(-" "sym=" "sym=val"
)
export valid_AMX_OPTION

resetVariable() {
    compiler_MODE="false"
    COMPILER_PAWNCC=""
    COMPILER_NEXT=0
    SERVERS_NEXT=0
    __SAMP_NEXT_QUERY=0
}

ignore_this() {
    "$@" > /dev/null 2>&1
}
export ignore_this

# shellcheck source=/dev/null

loaded_all_modules()
{
function load_module() {
    local module_name=$1
    local module_path="$shell_DIR/$module_name"
    local module_url=$2
    local special_param=$3

    if [ -f "$module_path" ] && [ "$DO_NOT_SHOW_LNOT" != 1 ]; then
        chmod +x "$module_path"
        if [ "$module_name" == ".workspace.py" ]; then
            source <(python3 .workspace.py) || echo
        else
            source "$module_path"
        fi

        clear

        if [ "$special_param" == "compat" ]; then 
            __handleOS ""
        fi
    else
        DO_NOT_SHOW_LNOT=1
        bash_title "Waiting resources.."
        echo -e "$(bash_coltext_y "info:") $module_name not found!. Installing.."
        ignore_this sleep 0.10 && clear

        mkdir -p "$shell_DIR"

        if ! wget -q --show-progress -O "$module_path" "$module_url"; then
            echo -e "$(bash_coltext_r "Failed: Check the official Triops repository before Sync.")"
        fi
        if [ "$special_param" == "compiler" ]; then
            __SAVE_RESET=1
        fi
        clear
    fi
}

load_module ".workspace.py" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Scripts/workspace.py" ""
load_module ".lib/security.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Security/security.io" ""
load_module ".lib/compat.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Compat/compat.io" "compat"
load_module ".lib/tligpac.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/TligPac/tligpac.io" ""
load_module ".lib/samp.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Package/samp.io" ""
load_module ".lib/pawncc.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Package/pawncc.io" ""
load_module ".lib/misc.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Misc/misc.io" "" 
load_module ".lib/server.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Server/server.io" ""
load_module ".lib/compiler.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Compiler/compiler.io" "compiler"

clear
}

function bash_typeof() {
    : '
        @mode.Typeof
    '
        
    if [ $MODULE_LOADED_NOTICE != 1 ]; then
        loaded_all_modules ""
        MODULE_LOADED_NOTICE=1
    fi

    if [ $__SAVE_RESET == 1 ]; then
        ignore_this sleep 0.100
        chmod +x "$shell_NAME"
        bash ./"$shell_NAME"
    fi

    : '
        @Send.Permissions.Typing
    '

    missing=()
    for cmd in python3 grep awk sed tr; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done

    if ((${#missing[@]})); then
        echo "Missing packages: ${missing[*]}"
        echo "Install first! See: https://github.com/vilksons/triops/wiki/Required-Packages"
        bash
    fi
    
    save_TITLE "OPS Mode"

    main_commands=""
    unset main_commands

    sleep 0.1
    
    echo -n "$(bash_coltext_y "$SHUSERS")"
    echo -n ":~$ "
    read -r main_commands

    mode_TRIOPS "" &&
    resetVariable ""
}
export bash_typeof

mode_TRIOPS() {
    : '
        @Send.OPS-Mode
    '

    local commands_TRIGGER="ops"

    case "$main_commands" in
        "compile"*)
            save_TITLE "Compiler"

            if [ $__DARWIN == 1 ]; then
                ignore_this docker stop $__SAMP_EXEC
            elif [ "$__LINUX" == 1 ] || [ "$__WINDOWS" == 1 ]; then 
                if [ -f "$save_LOCK_NAME_SERVER" ]; then
                    PID=$(cat "$save_LOCK_NAME_SERVER")
                    ignore_this kill -9 "$PID"
                    cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                    ignore_this rm "$save_LOCK_NAME_SERVER"
                fi
            fi
            
            local commands_ARGS="${main_commands#compile }"
            commands_INPUT=""
            commands_OPAMX=()

            for arg in $commands_ARGS; do
                if [ -z "$commands_INPUT" ]; then
                    commands_INPUT="$arg"
                else
                    commands_OPAMX+=("$arg")
                fi
            done

            local amx_valid=false

            if [[ "$main_commands" == "compile" ]]; then
                compiler_MODE="true"
                triops_compilers ""
            else
                if [[ -n "$commands_INPUT" ]]; then
                    if [[ "$commands_INPUT" == "." ]]; then
                        compiler_MODE="true"
                        triops_compilers ""
                    else
                        if [[ ${#commands_OPAMX[@]} -eq 0 ]]; then
                            COMPILER_NEXT=1
                        else
                            amx_valid=true

                            for option in "${commands_OPAMX[@]}"; do
                                if [[ " ${valid_AMX_OPTION[*]} " != *" $option "* ]]; then
                                    echo -e "$(bash_coltext_r "crit:") compiler option \`$option\` not found!"
                                    echo -e "$(bash_coltext_y "info:") please see: github.com/vilksons/triops/wiki/Compiler-Option"
                                    amx_valid=false
                                    bash_end ""
                                fi
                            done

                            if $amx_valid; then
                                COMPILER_NEXT=2
                            fi
                        fi
                    fi
                fi

                while IFS= read -r -d '' pawncc; do
                if [ -f "$pawncc" ]; then
                    COMPILER_PAWNCC="$pawncc"
                    break
                fi
                done < <(find "$shell_DIR" -type f -iname "$__PAWNCC" -print0)

                if [ -z "$COMPILER_PAWNCC" ]; then
                    echo -e "$(bash_coltext_r "crit:") $__PAWNCC not found!. You can get this in \`pawncc\`"
                    echo
                    read -r -p "install now? [y/n] " INSTALL_NOW

                    while true; do
                        case "$INSTALL_NOW" in
                            [Yy])
                                what_is_choice_pawncc ""
                                ;;
                            [Nn])
                                bash_typeof ""
                                ;;
                            *)
                                what_is_choice_pawncc ""
                                ;;
                        esac
                    done
                fi

                if ! find "$shell_DIR" -type f -name "$commands_INPUT" | grep -q .; then
                    echo -e "$(bash_coltext_r "crit:") $commands_INPUT not found!."
                    bash_typeof ""
                fi

                : '
                    @Map
                '
                __files=()
                while IFS= read -r -d '' COMPILED_FILES; do
                    __files+=("$COMPILED_FILES")
                done < <(find "$shell_DIR" -name "$commands_INPUT" -type f -print0)

                for COMPILED_FILES in "${__files[@]}"; do
                    if [ -f "$COMPILED_FILES" ] && [[ "$COMPILED_FILES" != *.amx ]]; then
                        bash_title "$COMPILED_FILES"

                        AMX_O="$(dirname "$COMPILED_FILES")/$(basename "${COMPILED_FILES%.*}.amx")"

                        echo -e "$(bash_coltext_y "dbg:") Processing: $COMPILED_FILES"

                        : '
                            @PawnCC.Compile
                        '
                        
                        __SPECIAL_INCLUDE_DIR=$(find "gamemodes" -type d | tr '\n' ':')
                        __SPECIAL_INCLUDE_DIR=${INCLUDE_DIRS%:}
                    
                        start_time=$(date +%s%3N)

                            for _ in {1..10}; do
                                if [ $COMPILER_NEXT == 1 ]; then
                                    "$COMPILER_PAWNCC" -i"$DEF_INCLUDE" "$DEF_EXCLUDE" -i"$__SPECIAL_INCLUDE_DIR" "$COMPILED_FILES" -o"$AMX_O" "$AMX_OPT_F" > "$__cache_save" 2>&1
                                elif [ $COMPILER_NEXT == 2 ]; then
                                    "$COMPILER_PAWNCC" -i"$DEF_INCLUDE" "$DEF_EXCLUDE" -i"$__SPECIAL_INCLUDE_DIR" "$COMPILED_FILES" -o"$AMX_O" "$AMX_OPT_F" "${commands_OPAMX[@]}" > "$__cache_save" 2>&1
                                fi
                            done
                            
                        end_time=$(date +%s%3N)

                        elapsed=$((end_time - start_time))
                        avg_time=$((elapsed / 10))
                        
                        bash_cache_compiler ""
                        ignore_this sleep 0.1 &&
                        cat "$__cache_save"

                        if [ -s "$AMX_O" ]; then
                            echo
                            echo "~ $AMX_O"
                            if [ "$compiler_MODE" == "true" ]; then
                                shell_TITLE="compilers"
                                bash_title "$SHUSERS:~/ $shell_TITLE"
                            elif [ "$compiler_MODE" == "false" ]; then
                                shell_TITLE="compiler - running"
                                bash_title "$SHUSERS:~/ $shell_TITLE"
                            fi
                            echo
                            echo "total size: $(stat -c%s "$AMX_O") bytes"
                            if [ $COMPILER_NEXT == 2 ]; then
                                echo -n "with +option compiler: "
                                echo "${commands_OPAMX[@]}"
                            fi
                            echo "Total execution time: ${elapsed} ms"
                            echo "Average time per iteration: ${avg_time} ms"
                        fi
                    fi
                done
            fi

            bash_end ""
            ;;
        "running"*)
            save_TITLE "Running"

            if [ $__DARWIN == 1 ]; then
                ignore_this docker stop $__SAMP_EXEC
            elif [ "$__LINUX" == 1 ] || [ "$__WINDOWS" == 1 ]; then 
                if [ -f "$save_LOCK_NAME_SERVER" ]; then
                    PID=$(cat "$save_LOCK_NAME_SERVER")
                    ignore_this kill -9 "$PID"
                    cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                    ignore_this rm "$save_LOCK_NAME_SERVER"
                fi
            fi
            
            local commands_ARGS="${main_commands#running }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                space_servers ""
            fi

            SERVERS_NEXT=1

            if [ "$commands_INPUT" == "." ]; then
                space_servers ""
            else
                if [ $__SAMP_SERVER == 0 ]; then
                    echo "err: this not allowed if SA-MP not Detected!"
                    bash_end ""
                fi
                space_wargs_servers "$commands_INPUT"
            fi
            bash_end ""
            ;;
        "irunn")
            save_TITLE "Compile & Running"

            if [ $__DARWIN == 1 ]; then
                ignore_this docker stop $__SAMP_EXEC
            elif [ "$__LINUX" == 1 ] || [ "$__WINDOWS" == 1 ]; then 
                if [ -f "$save_LOCK_NAME_SERVER" ]; then
                    PID=$(cat "$save_LOCK_NAME_SERVER")
                    ignore_this kill -9 "$PID"
                    cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                    ignore_this rm "$save_LOCK_NAME_SERVER"
                fi
            fi

            compiler_MODE="false"
            triops_compilers ""

            space_servers ""
            ;;
        "debug"*)
            save_TITLE "Debugging"

            if [ $__DARWIN == 1 ]; then
                ignore_this docker stop $__SAMP_EXEC
            elif [ "$__LINUX" == 1 ] || [ "$__WINDOWS" == 1 ]; then 
                if [ -f "$save_LOCK_NAME_SERVER" ]; then
                    PID=$(cat "$save_LOCK_NAME_SERVER")
                    ignore_this kill -9 "$PID"
                    cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                    ignore_this rm "$save_LOCK_NAME_SERVER"
                fi
            fi

            local commands_ARGS="${main_commands#debug }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                if [ $__SAMP_SERVER == 0 ]; then
                    echo "err: this not allowed if SA-MP not Detected!"
                    bash_end ""
                fi
                commands_INPUT="$commands_ARGS"
            else
                echo -e "$(bash_coltext_a ":: Enter GM Name:")"
                read -r -p ">>> " commands_INPUT

                echo -e "$(bash_coltext_a ":: Enter GM Name:")"
                while true; do
                    read -r -p ">>> " commands_INPUT
                    [[ -n "$commands_INPUT" ]] && break
                done
            fi

            SERVERS_NEXT=2
            
            if [ "$commands_INPUT" == "." ]; then
                space_servers ""
            else
                space_wargs_servers "$commands_INPUT"
            fi
            bash_end ""
            ;;
        "stop")
            save_TITLE "Stop"

            if [ $__DARWIN == 1 ]; then
                ignore_this docker stop $__SAMP_EXEC
            elif [ "$__LINUX" == 1 ] || [ "$__WINDOWS" == 1 ]; then 
                if [ -f "$save_LOCK_NAME_SERVER" ]; then
                    PID=$(cat "$save_LOCK_NAME_SERVER")
                    ignore_this kill -9 "$PID"
                    cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                    ignore_this rm "$save_LOCK_NAME_SERVER"
                fi
            fi
            bash_end ""
            ;;
        "restart")
            save_TITLE "Restart"

            if [ $__DARWIN == 1 ]; then
                if docker ps --filter "$__SAMP_EXEC" | grep -q "$__SAMP_EXEC"; then
                    ignore_this docker stop $__SAMP_EXEC

                    ignore_this sleep 2
                    space_servers ""
                else
                    echo "error: No progress Server running."
                fi
            elif [ "$__LINUX" == 1 ] || [ "$__WINDOWS" == 1 ]; then 
                if [ -f "$save_LOCK_NAME_SERVER" ]; then
                    PID=$(cat "$save_LOCK_NAME_SERVER")
                    ignore_this kill -9 "$PID"
                    cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                    ignore_this rm "$save_LOCK_NAME_SERVER"

                    ignore_this sleep 2
                    space_servers ""
                else
                    echo "error: No progress Server running."
                fi
            fi

            bash_end ""
            ;;
        "gamemode")
            save_TITLE "Downloads | GameMode"

            what_is_choice_samp ""

            bash_end ""
            ;;
        "pawncc")
            save_TITLE "Downloads | PawnCC"

            what_is_choice_pawncc ""

            bash_end ""
            ;;
        "clear")
            clear; echo -ne "\033[3J"
            bash_typeof ""
            ;;
        "fcheck")
            save_TITLE "Folder check"

            bash_check_dir "filterscripts"
            bash_check_dir "gamemodes"
            bash_check_dir "scriptfiles"

            bash_end ""
            ;;
        "cat"*)
            save_TITLE "Cat"

            local commands_ARGS="${main_commands#cat }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                echo -e "$(bash_coltext_a ":: Enter File Name:")"
                read -r -p ">>> " commands_INPUT
            fi

            cat "$commands_INPUT"
            echo
            bash_end ""
            ;;
        "directory"*)
            save_TITLE "Directory - $shell_DIR"

            local commands_ARGS="${main_commands#directory }"
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                ls -a
                bash_end ""
            fi

            ignore_this cd "$commands_INPUT" && ls -a && shell_TITLE="directory - $shell_DIR" && bash_title "$SHUSERS:~/ $shell_TITLE" || echo
            bash_typeof ""
            ;;
        "ls")
            ls -a
            bash_typeof ""
            ;;
        "kill")
            save_TITLE "Kill"

            clear
            ignore_this sleep 0.100
            chmod +x "$shell_NAME"
            bash ./"$shell_NAME"
            ;;
        "sync")
            save_TITLE "Sync"

            __lat=$(curl -s "https://api.github.com/repos/vilksons/triops/commits/main" | grep -o '"sha": "[^"]*' | awk -F': "' '{print $2}')

            __cur=$(cat "$shell_DIR/.commits" 2>/dev/null)

            if [[ "$__lat" == "$__cur" ]]; then
                echo "warning: $shell_NAME is up to date, Nothing to do."
                bash_end ""
            else
                echo -e "$(bash_coltext_a ":: There is an update!. Commits: (SHA1): ")"
                echo "$__lat"
                
                read -r -n1 -p ":: Do you want to continue Sync Triops? [y/n] " PERMISSION_NEED_S

                [[ -z "$PERMISSION_NEED_S" ]] && PERMISSION_NEED_S="Y"

                while true; do
                    case "$PERMISSION_NEED_S" in
                        [Yy])
                            echo "Updating..."
                            
                            echo "$__lat" > "$shell_DIR/.commits"
                            
                            cd "$shell_DIR/.lib" >/dev/null 2>&1 || echo ""

                            wget -q --show-progress -O "security.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/Security/security.io"
                            wget -q --show-progress -O "compat.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/Compat/compat.io"
                            wget -q --show-progress -O "tligpac.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/TligPac/tligpac.io"
                            wget -q --show-progress -O "samp.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/Package/samp.io"
                            wget -q --show-progress -O "pawncc.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/Package/pawncc.io"
                            wget -q --show-progress -O "server.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/Server/server.io"
                            wget -q --show-progress -O "misc.io" "https://raw.githubusercontent.com/vilksons/triops/refs/heads/main/Tools/Misc/misc.io"
                            wget -q --show-progress -O "compiler.io" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Tools/Compiler/compiler.io"

                            ignore_this sleep 1 && cd "$shell_DIR" >/dev/null 2>&1 || echo ""

                            wget -q --show-progress -O ".workspace.py" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Scripts/workspace.py"
                            wget -q --show-progress -O "workspace" "https://raw.githubusercontent.com/vilksons/Triops/refs/heads/main/Scripts/workspace"
                            
                            echo "$__lat" > "$shell_DIR/.commits"

                            sleep 1 && bash ./workspace
                            ;;
                        *)
                            bash_end ""
                            break
                            ;;
                    esac
                done
            fi
            ;;
        "checksums"*)
            save_TITLE "Checksums"

            local commands_ARGS="${main_commands#checksums }"

            ignore_this cd "$shell_DIR" || echo ""

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                echo "sha1:" && sha1sum "$shell_NAME" && echo "sha256:" && sha256sum "$shell_NAME" && echo "md5:" && md5sum "$shell_NAME"
                bash_end ""
            fi

            for algo in $commands_INPUT; do
                if [[ "$algo" == "sha1" ]]; then
                    echo "sha1:" && sha1sum "$shell_NAME"
                elif [[ "$algo" == "sha256" ]]; then
                    echo "sha256:" && sha256sum "$shell_NAME"
                elif [[ "$algo" == "md5" ]]; then
                    echo "md5:" && md5sum "$shell_NAME"
                else
                    echo "Invalid option: $algo (use sha1, sha256, md5)"
                fi
            done

            bash_end ""
            ;;
        "exit"*)
            save_TITLE "Exit"

            local commands_ARGS="${main_commands#exit }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                commands_INPUT="$commands_ARGS"
            else
                ignore_this sleep 0.100 &&
                bash
            fi

            if [ -f "$save_LOCK_NAME" ]; then
                PID=$(cat "$save_LOCK_NAME")
                ignore_this kill -9 "$PID"
                cd "$shell_DIR" >/dev/null 2>&1 || echo "" 
                ignore_this rm "$save_LOCK_NAME"
            fi
            bash
            ;;
        "chatbot"*)
            save_TITLE "Chatbot"

            local commands_ARGS="${main_commands#chatbot }"

            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                commands_INPUT="$commands_ARGS"
            else
               	echo -e "$(bash_coltext_a ":: Enter Question:")"
                echo " -> enter \"exit\" to exit"
                read -r -p ">>> " commands_INPUT
            fi

            if [[ "$commands_ARGS" == "exit" ]]; then
                bash_end ""
            fi

            response=$(curl -s -X POST https://api.groq.com/openai/v1/chat/completions \
                -H "Authorization: Bearer $CHATBOT_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{
                    \"model\": \"$CHATBOT_MODEL\",
                    \"messages\": [
                        {
                        \"role\": \"system\",
                        \"content\": \"$CHATBOT_BIODATA\"
                        },
                        {
                        \"role\": \"user\",
                        \"content\": \"$commands_INPUT .. do not add markdown symbols (.md)\"
                        }
                    ],
                    \"temperature\": 1,
                    \"max_tokens\": 1024,
                    \"top_p\": 1,
                    \"stream\": false,
                    \"stop\": null
                    }")

                echo "$response" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('choices', [{}])[0].get('message', {}).get('content', 'Error: Key not found'))
except json.JSONDecodeError:
    print('Error: Invalid JSON')
"

            echo "----------------------------------"
            bash_end ""
            ;;
        "nano"*)
            if [ "$__DIS_GNU_NANO" == "false" ]; then
                save_TITLE "GNU/Nano"
                
                local commands_ARGS="${main_commands#nano }"

                if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                    commands_INPUT="$commands_ARGS"
                else
                    echo -e "$(bash_coltext_a ":: Enter File Name:")"
                    read -r -p ">>> " commands_INPUT
                fi

                nano "$commands_INPUT"
                bash_end ""
            else
                echo "error: $main_commands: command not found"
                bash_end ""
            fi
            ;;
        "remcac")
            save_TITLE "Remove Cache"

            echo -e "$(bash_coltext_a ":: Cache Dir: $shell_DIR/.cache")"
            read -r -p ":: Do you want to remove ALL files from cache? [y/n] " PERMISSION_NEED_RC

            [[ -z "$PERMISSION_NEED_RC" ]] && PERMISSION_NEED_RC="Y"

            while true; do
                case "$PERMISSION_NEED_RC" in
                    [Yy])
                        ignore_this cd "$shell_DIR" || echo ""
                        ignore_this rm ".cache" && ignore_this sleep 1

                        if [ ! -d ".cache" ]; then
                            mkdir ".cache"
                        fi

                        ignore_this sleep 0.100 &&
                        bash_end ""
                        break
                        ;;
                    *)
                        bash_end ""
                esac
            done
            ;;
        "fetch")
            fetch_now ""
            ;;
        "tligpac")
            mode_TLIGPAC ""
            bash_help2 ""
            ;;
        "help"* | "$commands_TRIGGER -h"* | "$commands_TRIGGER --h"*)
            local commands_ARGS="${main_commands#"$commands_TRIGGER -h "}"
            local commands_ARGS="${commands_ARGS#help }"
            local commands_ARGS="${commands_ARGS#"$commands_TRIGGER --h "}"

            declare -A descriptions=(
                ["compile"]=":: Compile a project - Usage: compile | (+) [<args>] [target]"
                ["running"]=":: Running a project - Usage: running | (+) [<args>] [target]"
                ["irunn"]=":: Compile & Running a project - Usage: irunn"
                ["debug"]=":: Debug a project - Usage: debug | (+) [<args>] [target]"
                ["stop"]=":: stop all running server progress - Usage: stop"
                ["restart"]=":: Restart all Server - Usage: restart"
                ["gamemode"]=":: Download GameModes SA-MP with Selection - Usage: gamemode"
                ["pawncc"]=":: Download PawnCC SA-MP with Selection - Usage: pawncc"
                ["clear"]=":: Clear Screen Terminal - Usage: clear"
                ["checksums"]=":: Checksums of Triops - Usage: checksums"
                ["fcheck"]=":: Checks Directory of SA-MP - Usage: fcheck"
                ["cat"]=":: Display a files to Triops Terminal - Usage: cat"
                ["kill"]=":: Kill a Triops Terminal - Usage: kill"
                ["exit"]=":: Exit/End Triops Terminal - Usage: exit | (+) [<args>] \"all\" to kill all tasks"
                ["directory"]=":: Display or Change Terminal Directory - Usage: directory | ls"
                ["update"]=":: Update/Upgrade/Sync Triops Shell up-to-date - Usage: sync"
                ["remcac"]=":: Remove cache \".cache\" Triops - Usage: remcac"
                ["chatbot"]=":: Chatbot Terminal - Usage: chatbot"
                ["nano"]=":: GNU/Nano Editor - Usage: nano"
                ["tligpac"]=":: Triops Mode to TligPac Mode - Usage: tligpac"
                ["fetch"]=":: Fetch Triops -> Usage: fetch"
            )
            
            if [[ -n "$commands_ARGS" && "$commands_ARGS" != "$main_commands" ]]; then
                if [[ -n "${descriptions[$commands_ARGS]}" ]]; then
                    if [[ "$commands_ARGS" == "nano" && "$__DIS_GNU_NANO" == "true" ]]; then
                        bash_help "invalid"
                    else
                        if [ "$commands_ARGS" == "compile" ]; then
                            echo "${descriptions[$commands_ARGS]}"
                            echo " Example: compile bare.pwn +option_amx"
                            echo " For Option. Please See: github.com/vilksons/triops/wiki/Compiler-Option"
                        else
                            echo "${descriptions[$commands_ARGS]}"
                        fi
                    fi
                else
                    bash_help "invalid"
                fi
            else
                bash_help ""
            fi

            bash_typeof ""
            ;;
        "$commands_TRIGGER")
            bash_help ""
            bash_typeof ""
            ;;
        "" | " ")
            bash_typeof ""
            ;;
        *)
            not_found ""
            ;;
    esac
}
export mode_TRIOPS

function not_found()
{
    echo "error: $main_commands: command not found"
    bash_typeof ""
}

function bash_help()
{
    : '
        @Send.Help
    '
    local check_param=$1

    if [ "$check_param" == "invalid" ]; then
        echo "Invalid!.. Please Use:"
    fi

    echo "Usage: ops <command> | help | -h | --h | [<commands>]"
    echo "Commands:"
    echo " compile, running, irunn (compile-run), debug (debugger)"
    echo " stop (stopped server), restart (restart server)"
    echo " gamemode, pawncc, clear (clear-screen), checksums"
    echo " fcheck (folder-checks), cat, tligpac, kill, directory"

    if [ "$__DIS_GNU_NANO" == "true" ]; then
        echo " sync (update/upgrade), exit, remcac, chatbot, fetch"
    else
        echo " sync (update/upgrade), exit, remcac, chatbot, nano, fetch"
    fi
}

function bash_help2()
{
    echo "Usage: ops <command> [<args>]"
    echo "Commands:"
    echo " install - Install/Reinstall Packages"
    echo " remove  - Remove Packages"
    echo " exit    - Exit TligPac Mode"
}

function bash_end() {
    echo -e "$(bash_coltext_y "# Press any key to return.")"
    read -r -n 1 -s
    bash_typeof ""
}

: '
    @summary: Main
'
bash_typeof ""
